### ISSUE TITLE
使用文档拼写错误

### ISSUE THREAD

**Issue by l745230** [pansyjs/react-watermark#1]
![image](https://user-images.githubusercontent.com/15940920/91278842-4fad2480-e7b7-11ea-9ae3-9d27568cfe26.png)

另外,亲测水印效果很好,点个👍

**Comment by wangxingkang** [comment]
谢谢反馈

**Comment by wangxingkang** [comment]
看了下 这样写也没啥问题 应该写成  WaterMark ?
